# Local PostgreSQL Database
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local-m8LYx6vSJhjme3cB # TODO: remove references to temp local dev credentials
      POSTGRES_DB: forecast
    ports:
      - 127.0.0.1:5432:5432
