// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hw.Data;

#nullable disable

namespace hw.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hw.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 47.674f,
                            Longitude = -122.1215f,
                            Temperature = 58.2f,
                            TemperatureUnit = 2
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 34.0522f,
                            Longitude = -118.2437f,
                            Temperature = 71.6f,
                            TemperatureUnit = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 40.7143f,
                            Longitude = -74.006f,
                            Temperature = 61.3f,
                            TemperatureUnit = 2
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 33.4484f,
                            Longitude = -112.074f,
                            Temperature = 90.1f,
                            TemperatureUnit = 2
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 38.9415f,
                            Longitude = -76.965f,
                            Temperature = 58.6f,
                            TemperatureUnit = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
